### ISSUE TITLE
Journal Comments are misplace - see previous issue 'true'

### ISSUE THREAD

**Issue by russell-davis** [msrusse/HumanityHospiceAndroid#6]
Adding a comment to a post has the same issue as the previous issue filed - The parent is set to true, rather than the post ID where the comment should be filed

![screen shot 2018-10-25 at 9 09 15 pm](https://user-images.githubusercontent.com/19596011/47540323-3c1e9300-d89a-11e8-90ef-b79950b760a1.png)

**Comment by msrusse** [comment]
@russell-davis this one

**Comment by russell-davis** [comment]
confirmed closed
