### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by russell-davis** [msrusse/HumanityHospiceAndroid#9]
Weird Bugs:
- [ ] Frame rate drop off when scrolling up on Journal Page

Viewing A specific Journal Post:
- [x] the entire screen needs to be scrollable. (Currently the main post is stuck to the top, and comments scroll) Posts with images cut off too much of the comments section and often make the comments area inaccessible.

Journal:
- [x] When editing a journal post that HAS an image, the image should be deleteable.
- [x] When editing a journal post that HAS an image, ‘Add Image’ should be hidden

Photo Album:
- [x] Journal posts not loading when Photo Album loads.
- [x] Title should be changed from ‘My Photo Album’ to just ‘Photo Album’

Misc:
- [x] App icon should match iOS
- [x] Signing out should finish the activity and the back button should not go back to the app
- [x] All Post text needs to be larger, for older eyes.
- [x] When editing the text of any post or comment, the text needs to be multi line and scrollable
- [x] Cancel button does not work when editing posts
- [x] Remove the flower icon from the edit post pop up

Menu:
- [x] ‘Contact Care Nurse’ should be hidden on all pages when user is Reader (check ‘Add Patient Page’)

Encouragement Board:
- [x] (x) button (when creating a new encouragement post) doesn’t work.
- [x] Hide ‘Attach Photo’ and ‘Cancel’ on Enc. Board creation page
- [x] Change ‘New Post’ (title for enc. board creation page) to ‘Compose’
- [x] Change ‘Post’ to ‘Send’ (enc board creation page)

Blocking:
- [x] make sure when a user is blocked, all their comments are removed from the patients posts.

**Comment by msrusse** [comment]
Journal posts not loading when Photo Album loads.
What? @russell-davis
